keys:
  # Users
  - &users:
    - &mrhappy200 3AF8AF8C2C5EC2EC
  # Hosts
  - &hosts:
    - &HappyPC age1ykhz9tz5sen5penge8zstxsses9yy9r63r9w3awjrr8lgsex7slsvd9naa
creation_rules:
  - path_regex: hosts/HappyPC/secrets.ya?ml$
    key_groups:
    - age:
      - *HappyPC
      pgp:
      - *mrhappy200

  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
    - age:
      - *HappyPC
      pgp:
      - *mrhappy200
