keys:
  # Users
  - &users:
    - &mrhappy200 4A98047683B8E5A7
  # Hosts
  - &hosts:
    - &HappyPC age1ykhz9tz5sen5penge8zstxsses9yy9r63r9w3awjrr8lgsex7slsvd9naa
    - &HappyChromebook age1jx9y46vtamfqwy3yf392y4dkw0r9zae3p0qej6egh7jrljkvzsdqz2cnqn
    - &Bootstrap age18cgpyhkjhmfpx8dkunlfl2snenvurkkv75ukt9s9ykeguge8wyxqxdh58v
creation_rules:
  - path_regex: hosts/HappyPC/secrets.ya?ml$
    key_groups:
    - age:
      - *HappyPC
      - *Bootstrap
      pgp:
      - *mrhappy200

  - path_regex: hosts/HappyChromebook/secrets.ya?ml$
    key_groups:
    - age:
      - *HappyChromebook
      - *Bootstrap
      pgp:
      - *mrhappy200

  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
    - age:
      - *HappyPC
      - *HappyChromebook
      - *Bootstrap
      pgp:
      - *mrhappy200
