keys:
  # Users
  - &users:
    - &mrhappy200 9C77AB4C9FDEF882
  # Hosts
  - &hosts:
    - &HappyPC age18helpvrf3e6ej2r20cd5kcvehxaqq4a359ctyv36z0pt0svdcg9qhzfps5
    - &HappyChromebook age1jx9y46vtamfqwy3yf392y4dkw0r9zae3p0qej6egh7jrljkvzsdqz2cnqn
    - &Bootstrap age1wx3t2akmezv3w3hf5zkn2ylqzv33x8sn6jd6xh9yyqafajx7nu4qh0ccrx

creation_rules:
  - path_regex: hosts/HappyPC/secrets.ya?ml$
    key_groups:
    - age:
      - *HappyPC
      - *Bootstrap
      pgp:
      - *mrhappy200

  - path_regex: hosts/HappyChromebook/secrets.ya?ml$
    key_groups:
    - age:
      - *HappyChromebook
      - *Bootstrap
      pgp:
      - *mrhappy200

  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
    - age:
      - *HappyPC
      - *HappyChromebook
      - *Bootstrap
      pgp:
      - *mrhappy200
