keys:
  # Users
  - &users:
    - &mrhappy200 3AF8AF8C2C5EC2EC
  # Hosts
  - &hosts:
    - &HappyPC age1ykhz9tz5sen5penge8zstxsses9yy9r63r9w3awjrr8lgsex7slsvd9naa
    - &euphrosyne age12vt0mctfutp2ge84tmhmcsknytjj8v6fsr2ysrjls9jkj0a7zasswg8kau
creation_rules:
  - path_regex: hosts/euprosyne/secrets.ya?ml$
    key_groups:
    - age:
      - *euphrosyne
      pgp:
      - *mrhappy200

  - path_regex: hosts/happypc/secrets.ya?ml$
    key_groups:
    - age:
      - *HappyPC
      pgp:
      - *mrhappy200

  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
    - age:
      - *HappyPC
      - *euphrosyne
      pgp:
      - *mrhappy200

