# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "aesni_intel"
    "cryptd"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [
    "thunderbolt"
    "usb_storage"
    "sd_mod"
  ];
  boot.kernelParams = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.kernelPackages = pkgs.linuxPackages_latest;

  fileSystems."/nix/persist" = {
    device = "/persist";
    fsType = "none";
    options = [ "bind" ];
    neededForBoot = true;
  };

  fileSystems."/home".neededForBoot = true;

  fileSystems."/etc/ssh" = {
    device = "/nix/persist/etc/ssh";
    fsType = "none";
    options = [ "bind" ];
  };

  fileSystems."/home/mrhappy200/.steam" = {
    device = "/persist/steam/.steam";
    fsType = "none";
    options = [ "bind" ];
    noCheck = true;
  };

  fileSystems."/home/mrhappy200/.local/share/Steam" = {
    device = "/persist/steam/.local/share/Steam";
    fsType = "none";
    options = [ "bind" ];
    noCheck = true;
  };
  fileSystems."/home/mrhappy200/.local/share/bottles" = {
    device = "/persist/home/mrhappy200/.local/share/bottles";
    fsType = "none";
    options = [ "bind" ];
    noCheck = true;
  };
  fileSystems."/home/mrhappy200/Games" = {
    device = "/persist/home/mrhappy200/Games";
    fsType = "none";
    options = [ "bind" ];
    noCheck = true;
  };

  systemd.tmpfiles.rules = [
    "d /persist/steam/.local/share/Steam 0750 mrhappy200 users -"
    "d /persist/steam/.steam 0750 mrhappy200 users -"
    "d /persist/home/mrhappy200/.local/share/bottles 0750 mrhappy200 users -"
    "d /persist/home/mrhappy200/Games 0750 mrhappy200 users -"
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp8s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp9s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
